name: fw_dltime
description: Get approximate download time given a target file size for download.
version: 0.0.1-dev.15
homepage: https://github.com/repolyo/fw_dltime.git

environment:
  sdk: '>=3.1.0-89.0.dev <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  cloud_firestore: ^4.7.0
  flutter:
    sdk: flutter
  flutter_internet_speed_test: ^1.4.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0